### ISSUE TITLE
Watchcartoononline unable to play videos

### ISSUE THREAD

**Issue by indritix** [spoyser/spoyser-repo#35]
Hi, unfortunately video playback is not working.
Running Krypton(alpha1) on RPI2 with OSMC.
Starting with Kodi 17, DVDPLAYER is now named VIDEOPLAYER, so I replaced it in the "default.py", still no success.
Note, since updating to Kodi v17, the videos didn't play(with or without the change of DVDPLAYER).
With Kodi16 it works fine.
Below the log error:
`ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'module' object has no attribute 'PLAYER_CORE_VIDEOPLAYER'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.watchcartoononline/default.py", line 436, in <module>
                                                PlayVideo(url, (not AUTOPLAY))
                                              File "/home/osmc/.kodi/addons/plugin.video.watchcartoononline/default.py", line 296, in PlayVideo
                                                player = XBMCPlayer(xbmc.PLAYER_CORE_VIDEOPLAYER)
                                            AttributeError: 'module' object has no attribute 'PLAYER_CORE_VIDEOPLAYER'
                                            -->End of Python script error report<--`

**Comment by spoyser** [comment]
Try changing it to just

player = XBMCPlayer()

**Comment by indritix** [comment]
Cool, that did the trick.
Thanks a lot!

**Comment by spoyser** [comment]
Thanks for the confirmation :)

**Comment by daniel-ntl** [comment]
hi, i'm new here, but i have problem with this watchcartoononline addon, it unable to play video, the addon version is 1.1.7 by dandy and the repo is kodil repo, it cannot play video just january 2018, last december 2017 the addon just fine, please help, thx again

**Comment by mcgregortr1974** [comment]
The same as daniel-ntl.

I'm running Kodi 17.3 on a T95x Android box and using the WatchCartoonsOnline version 1.1.7 by Dandymedia.

I'm able to browse the WatchCartoonOnline menus but when I select a file to watch nothing happens and the following Python error message appears in the Kodi Log:

(PythonToCppException): --> Python callback/script returned the following error <--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.watchcartoon_gw/default.py", line 275, in <module>
     elif mode == 100 : resolve(name,url,iconimage,description)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.watchcartoon_gw/default.py", line 198, in resolve
     request_url = re.compile('<iframe id="frameNew.+?" src="(.+?)"').findall(OPEN)[0]
IndexError: list index out of range
-->

Any help with this would be appreciated.

Cheers
