### ISSUE TITLE
Watchcartoononline script failed

### ISSUE THREAD

**Issue by ZInyui4492** [spoyser/spoyser-repo#36]
Installed v1.0.22 and when I go to run it it gives me a error I hope this error log is what you need to see. 

01:40:51 M: 26001408 WARNING: -->Python Initialized<--
01:40:55 M: 22712320   ERROR: Error Type: <type 'exceptions.AttributeError'>
01:40:56 M: 22642688   ERROR: Error Contents: 'module' object has no attribute 'File'
01:40:56 M: 22642688   ERROR: Traceback (most recent call last):
                                              File "Q:\plugins\video\Watch Cartoon Online\default.py", line 462, in <module>
                                                Main()
                                              File "Q:\plugins\video\Watch Cartoon Online\default.py", line 96, in Main
                                                html = utils.getHTML(URL)
                                              File "Q:\plugins\video\Watch Cartoon Online\wco_utils.py", line 105, in getHTML
                                                html = quicknet.getURL(url, 86400, agent=agent)
                                              File "Q:\plugins\video\Watch Cartoon Online\quicknet.py", line 72, in getURL
                                                addToCache(url, data)
                                              File "Q:\plugins\video\Watch Cartoon Online\quicknet.py", line 99, in addToCache
                                                f         = sfile.file(cachePath, 'w')
                                              File "Q:\plugins\video\Watch Cartoon Online\sfile.py", line 50, in file
                                                return xbmcvfs.File(filename, type)
                                            AttributeError: 'module' object has no attribute 'File'
01:40:56 M: 30568448   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://video/Watch Cartoon Online/
01:40:56 M: 30568448   ERROR: CGUIMediaWindow::GetDirectory(plugin://video/Watch Cartoon Online/) failed
01:40:56 M: 30892032 WARNING: XFILE::CVideoDatabaseDirectory::GetLabel - Unknown nodetype requested 6

**Comment by spoyser** [comment]
No idea on that one, xbmcvfs is a Kodi module and has previously always had a File method.

Are you running a Krypton nightly?

**Comment by ZInyui4492** [comment]
Running XBMC4Xbox 3.5.3
