### ISSUE TITLE
Super Favourites error on startup

### ISSUE THREAD

**Issue by mattmartinolc** [spoyser/spoyser-repo#42]
Not sure what is going on. When I start kodi on any of two windows machines, and one android machine all running kodi 16.1 Jarvis there is a message just after startup "Super Favourites error. Check log for more information". Yet the superfavourites lists all work and everything seems fine. Nothing I can find in the log either.

**Comment by mattmartinolc** [comment]
nevermind I got it to log finally .. my advancedsettings.xml was set to stop logging

`01:47:20 T:4108   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: Failed to import time because the import lockis held by another thread.
                                            Traceback (most recent call last):
                                              File "C:\Users\Beth\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\service.py", line 31, in <module>
                                                utils.verifyRunning()
                                              File "C:\Users\Beth\AppData\Roaming\Kodi\addons\plugin.program.super.favourites\utils.py", line 250, in verifyRunning
                                                day = datetime.datetime.today().day
                                            ImportError: Failed to import time because the import lockis held by another thread.
                                            -->End of Python script error report<--
`

**Comment by spoyser** [comment]
Thanks for that, caused due to a bug in Python itself, will add a work around and push ASAP.
It shouldn't cause too much of an issue (switching context menu on or off might not work, but everything else should be okay)

**Comment by spoyser** [comment]
Can you check 1.0.55 to see if problem resolved, hard for me to test as it doesn't error on my mahine

**Comment by mattmartinolc** [comment]
Problem seems to be solved now on all the affected machines (not all were affected). Keep up the good work
