### ISSUE TITLE
Unable to import playlist from iPlay

### ISSUE THREAD

**Issue by Ferrari248F1AQ** [spoyser/spoyser-repo#62]
Hi,
I'm trying to import a m3u playlist with iPlay but for every action made in this sub-menu I receive an error (Super favourites error - check log). This is the content of the log:

```
16:27:21.542 T:18446744071825652016 WARNING: CPythonInvoker(125): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
16:27:22.650 T:18446744071833979184   ERROR: GetDirectory - Error getting /storage/emulated/0/Documents/Super Favourites
16:27:22.783 T:18446744072078031152   ERROR: Joystick Translator: Can't find button button
16:27:59.449 T:18446744072000092464   ERROR: Previous line repeats 63 times.
16:27:59.450 T:18446744072000092464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.NameError'>
                                            Error Contents: global name 'xbmcgui' is not defined
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.super.favourites/default.py", line 3301, in <module>
                                                doRefresh = iPlaylistBrowse()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.super.favourites/default.py", line 2469, in iPlaylistBrowse
                                                playlist = playlist.getPlaylist()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.super.favourites/playlist.py", line 53, in getPlaylist
                                                playlist = xbmcgui.Dialog().browse(1, utils.GETTEXT(30148), 'files', PLAYLIST_EXT, False, False, root)
                                            NameError: global name 'xbmcgui' is not defined
                                            -->End of Python script error report<--
16:27:59.551 T:18446744072078031152   ERROR: GetDirectory - Error getting plugin://plugin.program.super.favourites/?index=0&mode=3500
16:27:59.638 T:18446744072078031152   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.program.super.favourites/?index=0&mode=3500) failed
```

I receive this error both on Android than on MacOSX. I'm using last stable release of Kodi (17.6). I tried with a downgrade with version on Kodi repository (1.0.43) but it's the same...

**Comment by spoyser** [comment]
Oops!
If you are up for editting a file youself, just add 
import xbmcgui

to the top of the playlist.py file
I will push an update when I get a channce

**Comment by Ferrari248F1AQ** [comment]
Yes, it worked! Simpler than I thought! 👍

**Comment by spoyser** [comment]
:+1:
